[tool.poetry]
name = "drool"
version = "0.0.3"
description = ""
authors = ["dm <git@defend.sh>"]
packages = [{include = "drool"}]

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
